url: https://y7kim.github.io
baseurl: 

# Site settings
title: Guayo Mena
email: hola@guayo.me
description: "Desarrollo web en Costa Rica. "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3fb0ac
  secondary: 173e43  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/guayomena
  - title: facebook
    url: http://facebook.com/guayomena
  - title: instagram 
    url: http://instagram.com/guayomena
  - title: github
    url: http://github.com/guayom
  - title: google-plus
    url: http://google.com/+GuayoMena

# Postal address (add as many lines as necessary)
address:
  - line: "San José, La Uruca"

# Build settings
markdown: kramdown
permalink: pretty